---
- name: Create /etc/containerd
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Check if /etc/containerd/config.toml exists
  stat:
    path: /etc/containerd/config.toml
  register: containerd_config

- name: Copy containerd configuration
  shell: "containerd config default > /etc/containerd/config.toml"
  args:
    warn: no
  tags: ['skip_ansible_lint']
  when: not containerd_config.stat.exists
  notify: restart containerd

- name: Enable containerd
  service:
    name: containerd
    enabled: true
