---
- name: Create /etc/containerd
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Copy containerd configuration
  shell: "containerd config default > /tmp/config.toml"
  args:
    warn: no
  tags: ['skip_ansible_lint']
  notify: clean up

- name: Override containerd configuration if changed
  copy:
    src: /tmp/config.toml
    dest: /etc/containerd/config.toml
    remote_src: yes
    owner: root
    group: root
    mode: '0644'
  register: containerd_config

- name: Enable containerd
  service:
    name: containerd
    enabled: true

- name: Restart containerd
  service:
    name: containerd
    state: restarted
  when: containerd_config.changed