- name: Install containerd on Ubuntu 18.04 / 20.04
  apt:
    name: containerd
    update_cache: yes
  when: (ansible_distribution_version.split(".") | join == "1804") or
        (ansible_distribution_version.split(".") | join == "2004")
