- name: Install on Ubuntu 18.04 / 20.04
  block:
    - name: Install containerd
      apt:
        name: containerd
        update_cache: yes
  when:
    - {{ ansible_distribution_version.split('.') | join }}" == "1804"
    - {{ ansible_distribution_version.split('.') | join }}" == "2004"
