---
# handlers file for ansible-role-containerd
- name: restart containerd
  service:
    name: containerd
    state: restarted

- name: clean up
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/config.toml