---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
lint: |
  yamllint .
  ansible-lint
platforms:
  - name: instance1
    box: centos/7
    memory: 2048
    cpus: 1

  - name: instance2
    box: generic/ubuntu1804
    memory: 2048
    cpus: 1
    
  - name: instance3
    box: generic/ubuntu2004
    memory: 2048
    cpus: 1

provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
